import type {FoodItem,Category} from '../../types/index'

const basePath = import.meta.env.BASE_URL

export const categories: Category[] = [
  {
    id: 1,
    name: 'Burgers',
    items: [
      {
        id: 1,
        name: 'Classic Burger',
        image: `${basePath}cheese-burger.png`,
        price: 15.99,
        prep_time: 15,
        review: { avg_rating: 4.5, count: 120 },
        is_favorite: false,
      },
      {
        id: 2,
        name: 'Cheese Burger',
        image: `${basePath}cheese-burger.png`,
        price: 17.99,
        prep_time: 18,
        review: { avg_rating: 4.7, count: 95 },
        is_favorite: true,
      },
      {
        id: 3,
        name: 'Chicken Burger',
        image: `${basePath}cheese-burger.png`,
        price: 16.99,
        prep_time: 20,
        review: { avg_rating: 4.3, count: 78 },
        is_favorite: false,
      },
      {
        id: 4,
        name: 'Bacon Burger',
        image: `${basePath}cheese-burger.png`,
        price: 19.99,
        prep_time: 22,
        review: { avg_rating: 4.6, count: 85 },
        is_favorite: true,
      },
      {
        id: 5,
        name: 'Veggie Burger',
        image: `${basePath}cheese-burger.png`,
        price: 14.99,
        prep_time: 16,
        review: { avg_rating: 4.2, count: 65 },
        is_favorite: false,
      },
      {
        id: 6,
        name: 'Double Cheese Burger',
        image: `${basePath}cheese-burger.png`,
        price: 21.99,
        prep_time: 25,
        review: { avg_rating: 4.8, count: 110 },
        is_favorite: true,
      },
    ],
  },
  {
    id: 2,
    name: 'Pizza',
    items: [
      {
        id: 7,
        name: 'Margherita Pizza',
        image: `${basePath}pizza.png`,
        price: 22.99,
        prep_time: 25,
        review: { avg_rating: 4.6, count: 150 },
        is_favorite: false,
      },
      {
        id: 8,
        name: 'Pepperoni Pizza',
        image: `${basePath}pizza.png`,
        price: 24.99,
        prep_time: 30,
        review: { avg_rating: 4.8, count: 200 },
        is_favorite: true,
      },
      {
        id: 9,
        name: 'BBQ Chicken Pizza',
        image: `${basePath}pizza.png`,
        price: 26.99,
        prep_time: 28,
        review: { avg_rating: 4.7, count: 135 },
        is_favorite: false,
      },
      {
        id: 10,
        name: 'Supreme Pizza',
        image: `${basePath}pizza.png`,
        price: 28.99,
        prep_time: 35,
        review: { avg_rating: 4.9, count: 180 },
        is_favorite: true,
      },
      {
        id: 11,
        name: 'Hawaiian Pizza',
        image: `${basePath}pizza.png`,
        price: 25.99,
        prep_time: 32,
        review: { avg_rating: 4.4, count: 95 },
        is_favorite: false,
      },
      {
        id: 12,
        name: 'Meat Lovers Pizza',
        image: `${basePath}pizza.png`,
        price: 29.99,
        prep_time: 38,
        review: { avg_rating: 4.8, count: 160 },
        is_favorite: true,
      },
      {
        id: 13,
        name: 'Vegetarian Pizza',
        image: `${basePath}pizza.png`,
        price: 23.99,
        prep_time: 26,
        review: { avg_rating: 4.3, count: 75 },
        is_favorite: false,
      },
    ],
  },
  {
    id: 3,
    name: 'Asian Food',
    items: [
      {
        id: 14,
        name: 'Chicken Biryani',
        image: `${basePath}bryani.png`,
        price: 18.99,
        prep_time: 35,
        review: { avg_rating: 4.4, count: 85 },
        is_favorite: false,
      },
      {
        id: 15,
        name: 'Bro Special',
        image: `${basePath}bryani.png`,
        price: 19.99,
        prep_time: 25,
        review: { avg_rating: 4.9, count: 65 },
        is_favorite: true,
      },
      {
        id: 16,
        name: 'Beef Biryani',
        image: `${basePath}bryani.png`,
        price: 21.99,
        prep_time: 40,
        review: { avg_rating: 4.6, count: 95 },
        is_favorite: false,
      },
      {
        id: 17,
        name: 'Vegetable Biryani',
        image: `${basePath}bryani.png`,
        price: 16.99,
        prep_time: 30,
        review: { avg_rating: 4.2, count: 55 },
        is_favorite: false,
      },
      {
        id: 18,
        name: 'Mutton Biryani',
        image: `${basePath}bryani.png`,
        price: 24.99,
        prep_time: 45,
        review: { avg_rating: 4.7, count: 70 },
        is_favorite: true,
      },
      {
        id: 19,
        name: 'Fish Biryani',
        image: `${basePath}bryani.png`,
        price: 22.99,
        prep_time: 38,
        review: { avg_rating: 4.5, count: 60 },
        is_favorite: false,
      },
      {
        id: 20,
        name: 'Egg Biryani',
        image: `${basePath}bryani.png`,
        price: 17.99,
        prep_time: 28,
        review: { avg_rating: 4.3, count: 45 },
        is_favorite: false,
      },
      {
        id: 21,
        name: 'Hyderabadi Biryani',
        image: `${basePath}bryani.png`,
        price: 23.99,
        prep_time: 42,
        review: { avg_rating: 4.8, count: 80 },
        is_favorite: true,
      },
    ],
  },
  {
    id: 4,
    name: 'Fast Food',
    items: [
      {
        id: 22,
        name: 'Chicken Wings',
        image: `${basePath}cheese-burger.png`,
        price: 12.99,
        prep_time: 20,
        review: { avg_rating: 4.5, count: 100 },
        is_favorite: false,
      },
      {
        id: 23,
        name: 'French Fries',
        image: `${basePath}cheese-burger.png`,
        price: 8.99,
        prep_time: 12,
        review: { avg_rating: 4.2, count: 150 },
        is_favorite: true,
      },
      {
        id: 24,
        name: 'Chicken Nuggets',
        image: `${basePath}cheese-burger.png`,
        price: 11.99,
        prep_time: 15,
        review: { avg_rating: 4.3, count: 85 },
        is_favorite: false,
      },
      {
        id: 25,
        name: 'Onion Rings',
        image: `${basePath}cheese-burger.png`,
        price: 9.99,
        prep_time: 14,
        review: { avg_rating: 4.1, count: 70 },
        is_favorite: false,
      },
    ],
  },
  {
    id: 5,
    name: 'Desserts',
    items: [
      {
        id: 26,
        name: 'Chocolate Cake',
        image: `${basePath}pizza.png`,
        price: 8.99,
        prep_time: 10,
        review: { avg_rating: 4.7, count: 120 },
        is_favorite: true,
      },
      {
        id: 27,
        name: 'Ice Cream',
        image: `${basePath}pizza.png`,
        price: 6.99,
        prep_time: 5,
        review: { avg_rating: 4.4, count: 200 },
        is_favorite: false,
      },
      {
        id: 28,
        name: 'Cheesecake',
        image: `${basePath}pizza.png`,
        price: 9.99,
        prep_time: 8,
        review: { avg_rating: 4.6, count: 90 },
        is_favorite: true,
      },
      {
        id: 29,
        name: 'Tiramisu',
        image: `${basePath}pizza.png`,
        price: 10.99,
        prep_time: 12,
        review: { avg_rating: 4.8, count: 75 },
        is_favorite: false,
      },
    ],
  },
]
